apiVersion: v1
kind: Secret
metadata:
  name: voyage-db-secret
  namespace: voyage-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: dm95YWdlX3Bhc3N3b3Jk
  DB_USER: dm95YWFnZV91c2Vy
